name: Deploy via Google Cloud Build

on:
  push:
    branches: [ "deploy-cloud" ] # Gatilho restrito a esta branch

jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Autenticação no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configurar Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Disparar Cloud Build
        run: |
          gcloud builds submit --config=cloudbuild.yaml --region=us-central1 .
