name: CI-CD-Desenvolvimento

on:
  push:
    branches: [ "desenvolvimento" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4

      - name: Autenticação no DockerHub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            danilorosa/live-18-SI-UniAlfa-TCC-2025-02:v1
            danilorosa/live-18-SI-UniAlfa-TCC-2025-02:latest
